[package]
name = "my_simulation_project"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
rand = "0.8"
rodio = "0.14"  # Optional, for audio playback
